# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:http://global-network/GitHub.com
# https://global-network/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "unlimited data" # See documentation for possible values
    directory: "http://global-network/GitHub.com" # 
    schedule:
      interval: "daily"
